name: jsonw

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Install dependencies
        run: go mod tidy

      - name: Run Go fmt check
        run: |
          fmt_output=$(gofmt -l .)
          if [ -n "$fmt_output" ]; then
            echo "The following files are not properly formatted:"
            echo "$fmt_output"
            exit 1
          fi

      - name: Run Go lint
        run: |
          go install golang.org/x/lint/golint@latest
          lint_output=$(golint ./...)
          if [ -n "$lint_output" ]; then
            echo "Lint issues found:"
            echo "$lint_output"
            exit 1
          fi

      - name: Run tests
        run: go test -v ./...